from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file_path = Path(path)
    text = file_path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one patch target, found {count}")
    file_path.write_text(text.replace(old, new), encoding="utf-8")


replace_once(
    "src/building_hub.py",
    '''        url = self._optional_config_text(raw_url)\n        secret = self._optional_config_text(raw_secret)\n        if bool(url) != bool(secret):\n            raise BuildingHubValidationError(\n                "BUILDING_HUB_RELAY_URL and BUILDING_HUB_RELAY_HMAC_SECRET "\n                "must be configured together"\n            )\n        if url is None:\n            return None\n\n        return _RelayConfig(\n            base_url=self._validate_relay_url(url),\n            hmac_secret=self._validate_relay_hmac_secret(secret),\n        )\n''',
    '''        url = self._optional_config_text(raw_url)\n        secret = self._optional_config_text(raw_secret)\n        if url is None:\n            if secret is not None:\n                raise BuildingHubValidationError(\n                    "BUILDING_HUB_RELAY_URL is required when "\n                    "BUILDING_HUB_RELAY_HMAC_SECRET is configured"\n                )\n            return None\n\n        if secret is None:\n            # Avoid a second Streamlit secret for the free relay.  Both the\n            # Streamlit backend and Worker derive the same domain-separated\n            # HMAC key from the existing BuildingHUB service key.  The service\n            # key itself is never sent in the relay request.\n            secret = hashlib.sha256(\n                f"buildinghub-relay-v1\\x00{self._service_key}".encode("utf-8")\n            ).hexdigest()\n\n        return _RelayConfig(\n            base_url=self._validate_relay_url(url),\n            hmac_secret=self._validate_relay_hmac_secret(secret),\n        )\n''',
)

replace_once(
    "tests/test_building_hub.py",
    '''def test_relay_configuration_requires_complete_secure_pair(monkeypatch: pytest.MonkeyPatch) -> None:\n    monkeypatch.setenv("BUILDING_HUB_RELAY_URL", RELAY_URL)\n    monkeypatch.delenv("BUILDING_HUB_RELAY_HMAC_SECRET", raising=False)\n\n    with pytest.raises(BuildingHubValidationError, match="configured together"):\n        BuildingHubClient(KEY, session=FakeSession())\n\n    with pytest.raises(BuildingHubValidationError, match="HTTPS"):\n        BuildingHubClient(\n            KEY,\n            session=FakeSession(),\n            relay_url="http://relay.example.com",\n            relay_hmac_secret=RELAY_SECRET,\n        )\n\n    with pytest.raises(BuildingHubValidationError, match="at least 32"):\n        BuildingHubClient(\n            KEY,\n            session=FakeSession(),\n            relay_url=RELAY_URL,\n            relay_hmac_secret="too-short",\n        )\n''',
    '''def test_relay_configuration_can_derive_secret_from_existing_service_key(\n    monkeypatch: pytest.MonkeyPatch,\n) -> None:\n    monkeypatch.setenv("BUILDING_HUB_RELAY_URL", RELAY_URL)\n    monkeypatch.delenv("BUILDING_HUB_RELAY_HMAC_SECRET", raising=False)\n    session = FakeSession(\n        requests.ConnectionError("direct DNS lookup failed"),\n        FakeResponse(payload=api_payload({"id": "derived-secret"})),\n    )\n    client = BuildingHubClient(KEY, session=session, max_retries=0)\n\n    assert client.relay_enabled is True\n    assert client.fetch_all("getBrTitleInfo", LAND_DICT) == [{"id": "derived-secret"}]\n    relay_call = session.calls[1]\n    derived_secret = hashlib.sha256(\n        f"buildinghub-relay-v1\\x00{KEY}".encode("utf-8")\n    ).hexdigest()\n    headers = relay_call["headers"]\n    signed = (\n        f"{headers['X-Building-Hub-Timestamp']}\\n"\n        f"{headers['X-Building-Hub-Nonce']}\\n"\n        f"getBrTitleInfo\\n{relay_call['data']}"\n    ).encode("utf-8")\n    expected_signature = hmac.new(\n        derived_secret.encode("utf-8"), signed, hashlib.sha256\n    ).hexdigest()\n    assert headers["X-Building-Hub-Signature"] == expected_signature\n    assert KEY not in relay_call["data"]\n    assert KEY not in str(headers)\n\n\ndef test_relay_configuration_validation_still_rejects_unsafe_values() -> None:\n    with pytest.raises(BuildingHubValidationError, match="HTTPS"):\n        BuildingHubClient(\n            KEY,\n            session=FakeSession(),\n            relay_url="http://relay.example.com",\n            relay_hmac_secret=RELAY_SECRET,\n        )\n\n    with pytest.raises(BuildingHubValidationError, match="at least 32"):\n        BuildingHubClient(\n            KEY,\n            session=FakeSession(),\n            relay_url=RELAY_URL,\n            relay_hmac_secret="too-short",\n        )\n\n    with pytest.raises(BuildingHubValidationError, match="RELAY_URL"):\n        BuildingHubClient(\n            KEY,\n            session=FakeSession(),\n            relay_hmac_secret=RELAY_SECRET,\n        )\n''',
)
